<?php

namespace AppBundle\Entity;

/**
 * PostAttributesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostAttributesRepository extends \Doctrine\ORM\EntityRepository
{
}
