<?php

namespace AppBundle\Entity;

/**
 * PostMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostMetaRepository extends \Doctrine\ORM\EntityRepository
{
}
